### ISSUE TITLE
Allow ability to control CRT logs

### ISSUE THREAD

**Issue by ganeshnj** [smithy-lang/smithy-swift#526]
### Describe the feature

Currently disabled under https://github.com/awslabs/smithy-swift/blob/c52ebe82a1431f3f35626f7e7d8c6e232f0aaac6/Sources/ClientRuntime/Networking/Http/CRT/SDKDefaultIO.swift#L28

### Use Case

Logging.

### Proposed Solution

Two options
- use SDK level config for CRT logs
~~ - I prefer this but it can be too much for someone who just wants SDK logs ~~ not possible
- use different config

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ganeshnj** [comment]
CRT logging can only be applied once in the application. if this is the case, we have to have a global configuration.

**Comment by dayaffe** [comment]
Will be tracked in [#1131](https://github.com/awslabs/aws-sdk-swift/issues/1131)
