### ISSUE TITLE
Smithy Swift support for VisionOS

### ISSUE THREAD

**Issue by lastw0nd3r** [smithy-lang/smithy-swift#603]
### Describe the feature

Wondering if you guys can add support for visionOS, should work the same way for iOS as you aren't using UIKit.

### Use Case

I was trying to use AWS-SDK and it's referencing (as a package dependency) to smithy swift. But, the latest/any version doesn't support visionOS.

Maybe you can add an #elseif in PlatformOperatingSystem.swift (should behave the same way as iOS).

### Proposed Solution

Maybe you can add an #elseif in PlatformOperatingSystem.swift (should behave the same way as iOS).

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by dayaffe** [comment]
Thanks for your issue, we'll look into it & will update this issue when we have more info

**Comment by dayaffe** [comment]
We're going to allow the SDK to compile and you can expect this to be in the next release! However, we do not guarantee that it will work and cannot provide additional support at this time. Please let us know how it goes!

**Comment by lastw0nd3r** [comment]
I have tried changing the header file in here to use "iOS" for "VisionOS" in the switch in PlatformOperatingSystem.swift and it works as expected. So, I believe if you'd keep "iOS" / "VisionOS" pointing to the same OS in that switch. That should be it. 

Thanks

**Comment by jbelkins** [comment]
@lastw0nd3r In AWS SDK for Swift 0.29.0 (released today), we have added visionOS as a PlatformOperatingSystem option.

We are adding it for experimentation purposes only and are not committing to long-term support of visionOS.  However, the changes we have made should allow the SDK to at least compile successfully when linked into a visionOS app.

Please feel free to share your feedback or file further issues regarding your experience with the SDK.
