### ISSUE TITLE
FileStream class is invisible for the framework user

### ISSUE THREAD

**Issue by MainasuK** [smithy-lang/smithy-swift#634]
### Describe the bug

We could use `ByteStream.from(data:)` or `ByteStream.from(fileHandle:)` create the `ByteStream` instance before [460e51c](https://github.com/smithy-lang/smithy-swift/commit/460e51c40b7853bc5254bad86cc70003bfc733f9). However, now the API use `ByteStream.data(Data?)` and `ByteStream.stream(Steam)`. But the `FileStream` class is not a **public** class so framework user cannot access it. to use `BytesStream.stream(FileStream(fileHandle:))`

### Expected Behavior

Make the `FileStream` class and init `public` for framework user. Or rollback the `ByteStream.from(fileHandle:)` method in 0.36.0.

### Current Behavior

The `FileStream` is default `internal`. The framework user cannot access it.

### Reproduction Steps

Migrate code `ByteStream.from(fileHandle:)` from old version (0.36.0) to new version (0.37.0) of the package.

### AWS SWIFT SDK version used

0.37.0

### Compiler and Version used

Version 15.1 (15C65)

### Operating System and version

14.2.1 (23C71)

**Comment by dayaffe** [comment]
Thank you for submitting this issue! We will investigate and provide updates on this thread.

**Comment by dayaffe** [comment]
#635 adds back the method `ByteStream.from(fileHandle:)`! This update will go out with the next release.
