### ISSUE TITLE
Unable to set up SDKLoggingSystem

### ISSUE THREAD

**Issue by shepazon** [smithy-lang/smithy-swift#792]
### Describe the bug

Since the recent concurrency warning fixes, trying to use `SDKLoggingSystem` in a project fails. Specifically, if I put this code into my project:

```
    await SDKLoggingSystem.initialize(logLevel: .trace)
````

I get a compiler error: `Instance member 'initialize' cannot be used on type 'SDKLoggingSystem'; did you mean to use a value of this type instead?`.

If I try to create a value of type `SDKLoggingSystem` like this:

```
    let loggingSystem = SDKLoggingSystem()
```

I get this compiler error instead: `'SDKLoggingSystem' initializer is inaccessible due to 'internal' protection level`

### Expected Behavior

The logging system should be able to be initialized and used, but cannot be.

### Current Behavior

Errors described in description.

### Reproduction Steps

See description.

### Additional Information/Context

If I back my code up to an earlier version, such as 0.47.0

### AWS SWIFT SDK version used

0.49.0

### Compiler and Version used

Xcode 15.4, Swift 5.10.0

### Operating System and version

macOS 14.6

**Comment by sichanyoo** [comment]
Went out with the release of v0.58.0: https://github.com/smithy-lang/smithy-swift/releases/tag/0.58.0. Closing.
