### ISSUE TITLE
RetryStrategyOptions requires a backoff strategy, but...

### ISSUE THREAD

**Issue by shepazon** [smithy-lang/smithy-swift#818]
### Describe the bug

In the past, the backoff strategy component of `RetryStrategyOptions` was optional, with a default. It has become the only required property, which makes little sense since it's the one people are least likely to change (at least as far as I can tell). The comment even describes the default value.

But there's no way to say "use the default." There's no `DefaultBackoffStrategy`. So unless something is hiding somewhere, you have to create an `ExponentialBackoffStrategy` or a custom `RetryBackoffStrategy` type, and specify that.

Please make it so this is optional, and/or provide a default backoff strategy type you can instantiate and use here.

### Expected Behavior

To be able to change the number of retries without creating and specifying an exponential backoff strategy.

### Current Behavior

Too much thinking. Not enough getting it done.

### Reproduction Steps

```
        let config: S3Client.S3ClientConfiguration

        do {
            config = try await S3Client.S3ClientConfiguration(
                retryStrategyOptions: RetryStrategyOptions(
                    maxRetriesBase: 5,
                    rateLimitingMode: .adaptive
                )
            )
        } catch {
            dump(error)
        }
```

### Possible Solution

This used to work. Doesn't anymore. Would be nice not to have to add the `backoffStrategy` property to the options to get it to work.

### AWS SWIFT SDK version used

0.76.1

### Compiler and Version used

Swift version 5.10.1 (swift-5.10.1-RELEASE)

### Operating System and version

#23~22.04.1-Ubuntu

**Comment by sichanyoo** [comment]
For background info, refer to the GitHub issue that mentions this issue above (in ticket history).

The fix has been merged to main with this PR: https://github.com/awslabs/aws-sdk-swift/pull/1744.

Retry example and doc that discusses directly manipulating the `retryStrategyOptions` should be rewritten as soon as it is possible. The new example and doc should discuss manipulating the `awsRetryMode` and `maxAttempts` config options instead. which get automatically used to resolve the `retryStrategyOptions` used by the service client.

**Comment by sichanyoo** [comment]
The examples that use `awsRetryMode` and `maxAttempts` instead of directly manipulating `retryStrategyOptions` have replaced the old examples. Closing the ticket as resolved.
